name: Ingest Humanitec Integration Resources

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  ingest-humanitec-resources: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ingest Entities to Port
        env:
            PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
            PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
            HUMANITEC_API_TOKEN: ${{ secrets.HUMANITEC_API_TOKEN }}
            HUMANITEC_BASE_URL: ${{ secrets.HUMANITEC_BASE_URL }}
            HUMANITEC_ORG_ID: ${{secrets.HUMANITEC_ORG_ID }}    
        run: |
          python humanitec-exporter.py
